# Generated by Django 5.2.4 on 2025-07-20 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RebatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('policy_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('tiered', 'Tiered')], max_length=20)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('minimum_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rebate Policy',
                'verbose_name_plural': 'Rebate Policies',
            },
        ),
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebates', to='exchanges.referraltransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebates', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebates', to='rebates.rebatepolicy')),
            ],
            options={
                'verbose_name': 'Rebate',
                'verbose_name_plural': 'Rebates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RebatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rebate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rebates.rebate')),
            ],
            options={
                'verbose_name': 'Rebate Payment',
                'verbose_name_plural': 'Rebate Payments',
            },
        ),
        migrations.CreateModel(
            name='UserRebateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rebates', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_paid', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pending_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rebate_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rebate Summary',
                'verbose_name_plural': 'User Rebate Summaries',
            },
        ),
    ]
